import type { Metadata } from 'next';
import './globals.css';
import '@luno-kit/ui/styles.css';
import Providers from '@/app/providers';

export const metadata: Metadata = {
  title: 'LunoKit example',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
